<?php

namespace ContainerXXd7hOd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GSTSSxNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GSTSSxN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.GSTSSxN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'request' => ['privates', 'App\\Requests\\DeviceRequest', 'getDeviceRequestService', true],
        ], [
            'request' => 'App\\Requests\\DeviceRequest',
        ]);
    }
}
